// Copyright (C) Parity Technologies (UK) Ltd.
// This file is part of Individuality.

// Polkadot is free software: you can redistribute it and/or modify
// it under the terms of the GNU General Public License as published by
// the Free Software Foundation, either version 3 of the License.

// Individuality is distributed in the hope that it will be useful,
// but WITHOUT ANY WARRANTY; without even the implied warranty of
// MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
// GNU General Public License for more details.

// You should have received a copy of the GNU General Public License
// along with Individuality.  If not, see <http://www.gnu.org/licenses/>.

//! People lite.
//!
//! Warning: This pallet must be configured with some spam prevention mechanism.
//! The spam prevention mechanism must limit how many calls the origin
//! `LitePerson` can do.
//! The recommended approach is to use pallet-origins-restriction.

#![cfg_attr(not(feature = "std"), no_std)]
#![allow(clippy::borrowed_box)]
extern crate alloc;
use alloc::boxed::Box;

#[cfg(feature = "runtime-benchmarks")]
pub mod benchmarking;
pub mod extension;
pub mod weights;

#[cfg(test)]
mod mock;
#[cfg(test)]
mod tests;

pub use extension::{PeopleLiteAuth, PeopleLiteAuthData};
pub use pallet::*;
pub use weights::WeightInfo;

use frame_support::{
	dispatch::{DispatchResultWithPostInfo, PostDispatchInfo},
	traits::IsSubType,
};
use sp_runtime::traits::{Dispatchable, IdentifyAccount, Verify};
use verifiable::GenerateVerifiable;

#[frame_support::pallet]
pub mod pallet {
	use super::*;
	use frame_support::pallet_prelude::*;
	use frame_system::pallet_prelude::*;

	pub const MSG_PREFIX: &[u8; 30] = b"pop:people-lite:register using";

	// const LOG_TARGET: &str = "runtime::pallet-people-lite";

	pub type MemberOf<T> = <<T as Config>::Crypto as GenerateVerifiable>::Member;
	pub type SignatureOf<T> = <<T as Config>::Crypto as GenerateVerifiable>::Signature;

	/// The method through which the user was recognized as a lite person.
	#[derive(
		Encode, Decode, DecodeWithMemTracking, Clone, PartialEq, Eq, Debug, TypeInfo, MaxEncodedLen,
	)]
	pub enum RecognitionMethod<Account> {
		/// User has a unique device, corroborated by the attester.
		UniqueDevice(Account),
		// Voucher(PersonalId)
	}

	/// Information about a registered lite person.
	#[derive(
		Encode, Decode, DecodeWithMemTracking, Clone, PartialEq, Eq, Debug, TypeInfo, MaxEncodedLen,
	)]
	pub struct LitePersonInfo<Member, Method> {
		/// The user's ring vrf key.
		pub ring_vrf_key: Member,
		/// The method through which the user was registered.
		pub method: Method,
	}
	pub type LitePersonInfoOf<T> =
		LitePersonInfo<MemberOf<T>, RecognitionMethod<<T as frame_system::Config>::AccountId>>;

	#[pallet::pallet]
	pub struct Pallet<T>(_);

	#[pallet::config]
	pub trait Config:
		frame_system::Config<
		RuntimeOrigin: From<Origin<Self>> + OriginTrait<PalletsOrigin: TryInto<Origin<Self>>>,
		RuntimeCall: IsSubType<Call<Self>> + Dispatchable<PostInfo = PostDispatchInfo>,
	>
	{
		/// Weight information for extrinsics in this pallet.
		type WeightInfo: WeightInfo;

		/// The origin that can issue quotas to verifiers.
		type AttestationAllowanceManager: EnsureOrigin<Self::RuntimeOrigin>;

		/// Trait allowing cryptographic proof of membership without exposing the underlying member.
		/// Normally a Ring-VRF.
		type Crypto: GenerateVerifiable<
			Proof: Send + Sync + DecodeWithMemTracking,
			Signature: Send + Sync + DecodeWithMemTracking,
			Member: DecodeWithMemTracking,
		>;

		/// Signature generated by lite people and used by verifiers to claim attestations on their
		/// behalf.
		type AttestationSignature: Verify<Signer: IdentifyAccount<AccountId = Self::AccountId>>
			+ Parameter;

		/// A set of helper functions for benchmarking.
		///
		/// The default configuration `()` uses the `SR25519` signature schema.
		#[cfg(feature = "runtime-benchmarks")]
		type BenchmarkHelper: BenchmarkHelper<Self::AccountId, Self::AttestationSignature>;
	}

	#[pallet::origin]
	#[derive(
		CloneNoBound,
		PartialEqNoBound,
		EqNoBound,
		RuntimeDebugNoBound,
		Encode,
		Decode,
		MaxEncodedLen,
		TypeInfo,
		DecodeWithMemTracking,
	)]
	#[scale_info(skip_type_params(T))]
	pub enum Origin<T: Config> {
		/// A person litely recognized.
		LitePerson(T::AccountId),
	}

	#[pallet::storage]
	pub type LitePeople<T: Config> =
		StorageMap<_, Blake2_128Concat, T::AccountId, LitePersonInfoOf<T>>;

	/// Number of attestations available to distribute for a verifier account id.
	#[pallet::storage]
	pub(crate) type AttestationAllowance<T: Config> =
		StorageMap<_, Blake2_128Concat, T::AccountId, u32, ValueQuery>;

	#[pallet::event]
	#[pallet::generate_deposit(pub(super) fn deposit_event)]
	pub enum Event<T: Config> {
		/// All attestation allowance has been removed for the verifier.
		AllAttestationAllowanceCleared { verifier: T::AccountId },
	}

	#[pallet::error]
	pub enum Error<T> {
		/// No attestation allowance.
		NoAttestationAllowance,
		/// The signature created by the candidate's account is invalid.
		InvalidAttestationSignature,
		/// The signature created by the candidate's ring vrf key is invalid.
		InvalidProofOfOwnership,
		/// The candidate is already registered.
		AlreadyRegistered,
	}

	#[pallet::hooks]
	impl<T: Config> Hooks<BlockNumberFor<T>> for Pallet<T> {}

	#[pallet::call]
	impl<T: Config> Pallet<T> {
		/// Grant some attestation allowance to an account so they can attest people.
		///
		/// The origin must be `AttestationAllowanceManager`.
		///
		/// - `account`: The account to grant attestations to.
		/// - `count`: The number of attestations to grant.
		#[pallet::call_index(0)]
		#[pallet::weight(<T as Config>::WeightInfo::increase_attestation_allowance())]
		pub fn increase_attestation_allowance(
			origin: OriginFor<T>,
			account: T::AccountId,
			count: u32,
		) -> DispatchResult {
			T::AttestationAllowanceManager::ensure_origin(origin)?;
			let mut available = AttestationAllowance::<T>::get(&account);
			available = available.saturating_add(count);
			AttestationAllowance::<T>::insert(&account, available);
			Ok(())
		}

		/// Clear all attestation allowance for an account.
		///
		/// The origin must be `AttestationAllowanceManager`.
		///
		/// - `account`: The account to remove all attestations from.
		#[pallet::call_index(1)]
		#[pallet::weight(<T as Config>::WeightInfo::clear_attestation_allowance())]
		pub fn clear_attestation_allowance(
			origin: OriginFor<T>,
			account: T::AccountId,
		) -> DispatchResult {
			T::AttestationAllowanceManager::ensure_origin(origin)?;
			AttestationAllowance::<T>::remove(&account);
			Self::deposit_event(Event::AllAttestationAllowanceCleared { verifier: account });

			Ok(())
		}

		/// Attest an account.
		///
		/// The origin must be signed by an account and have some attestation allowance left.
		///
		/// The authority will have to get two signatures from the user:
		/// - one created using their account key attesting to the ownership of the `candidate`
		///   account;
		/// - one created using their ring-vrf key attesting to the ownership of the `ring_vrf_key`
		///   key.
		///
		/// The message to be signed by both keys from which the signatures are generated is created
		/// by concatenating the bytes "pop:people-lite:register using" with the encoded bytes of
		/// the user's account (`candidate`), and the encoded bytes of the ring VRF key
		/// (`ring_vrf_key`).
		///
		/// - `candidate`: The candidate to be recognized as a lite person.
		/// - `candidate_signature`: The signature, provided by the candidate, to allow the attester
		///   to complete the registration process on their behalf.
		/// - `ring_vrf_key`: The ring VRF key to be associated with the lite person.
		/// - `ring_vrf_key_signature`: The ring VRF signature, provided by the candidate, to allow
		///   the attester to complete the registration process. This also prove the ownership of
		///   the ring VRF key by the candidate.
		#[pallet::call_index(2)]
		#[pallet::weight(<T as Config>::WeightInfo::attest())]
		pub fn attest(
			origin: OriginFor<T>,
			candidate: T::AccountId,
			candidate_signature: T::AttestationSignature,
			ring_vrf_key: MemberOf<T>,
			proof_of_ownership: <T::Crypto as GenerateVerifiable>::Signature,
		) -> DispatchResultWithPostInfo {
			let verifier = ensure_signed(origin)?;
			ensure!(!LitePeople::<T>::contains_key(&candidate), Error::<T>::AlreadyRegistered);

			let mut available = AttestationAllowance::<T>::get(&verifier);
			available = available.checked_sub(1).ok_or(Error::<T>::NoAttestationAllowance)?;

			if available > 0 {
				AttestationAllowance::<T>::insert(&verifier, available);
			} else {
				AttestationAllowance::<T>::remove(&verifier);
			}

			// Verify the candidate's signature for the attestation.
			let msg = candidate.using_encoded(|c_bytes| {
				ring_vrf_key.using_encoded(|rv_bytes| [&MSG_PREFIX[..], c_bytes, rv_bytes].concat())
			});
			ensure!(
				candidate_signature.verify(&msg[..], &candidate),
				Error::<T>::InvalidAttestationSignature,
			);

			// Verify proof of ownership of the ring VRF key.
			ensure!(
				T::Crypto::verify_signature(&proof_of_ownership, &msg[..], &ring_vrf_key),
				Error::<T>::InvalidProofOfOwnership,
			);

			LitePeople::<T>::insert(
				&candidate,
				LitePersonInfo { ring_vrf_key, method: RecognitionMethod::UniqueDevice(verifier) },
			);
			frame_system::Pallet::<T>::inc_sufficients(&candidate);

			Ok(Pays::No.into())
		}

		#[pallet::call_index(5)]
		#[pallet::weight(
			<T as Config>::WeightInfo::dispatch_as_signer()
			.saturating_add(call.get_dispatch_info().call_weight)
		)]
		pub fn dispatch_as_signer(
			mut origin: OriginFor<T>,
			call: Box<T::RuntimeCall>,
		) -> DispatchResultWithPostInfo {
			let who = match origin.clone().into_caller().try_into() {
				Ok(Origin::LitePerson(account)) => account,
				_ => return Err(DispatchError::BadOrigin.into()),
			};

			origin.set_caller_from(frame_system::RawOrigin::Signed(who));

			call.dispatch(origin)
		}
	}

	/// Guard to ensure that the given origin is a lite person. The account of the lite person is
	/// provided on success.
	pub struct EnsureLitePerson<T>(PhantomData<T>);
	impl<T: Config> EnsureOrigin<OriginFor<T>> for EnsureLitePerson<T> {
		type Success = T::AccountId;

		fn try_origin(o: OriginFor<T>) -> Result<Self::Success, OriginFor<T>> {
			match o.clone().into_caller().try_into() {
				Ok(Origin::LitePerson(account)) => Ok(account),
				_ => Err(o),
			}
		}

		#[cfg(feature = "runtime-benchmarks")]
		fn try_successful_origin() -> Result<OriginFor<T>, ()> {
			let who = frame_benchmarking::account::<T::AccountId>("successful_origin", 0, 0);
			Ok(Origin::LitePerson(who).into())
		}
	}

	#[cfg(feature = "runtime-benchmarks")]
	pub trait BenchmarkHelper<AccountId, Signature> {
		fn sign_message(message: &[u8]) -> (AccountId, Signature);
	}
	#[cfg(feature = "runtime-benchmarks")]
	impl BenchmarkHelper<sp_runtime::AccountId32, sp_runtime::MultiSignature> for () {
		fn sign_message(message: &[u8]) -> (sp_runtime::AccountId32, sp_runtime::MultiSignature) {
			use sp_core::Pair;
			use sp_runtime::traits::IdentifyAccount;
			let entropy = [1u8; 32];
			let pair = sp_core::ed25519::Pair::from_seed(&entropy);
			let account = pair.public().into_account().into();
			let secret = ed25519_zebra::SigningKey::from(entropy);
			let signature = sp_core::ed25519::Signature::from_raw(secret.sign(message).into());
			(account, signature.into())
		}
	}
}
