// This file is part of Substrate.

// Copyright (C) Parity Technologies (UK) Ltd.
// SPDX-License-Identifier: Apache-2.0

// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
// 	http://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.


//! Autogenerated weights for `pallet_people_multi`
//!
//! THIS FILE WAS AUTO-GENERATED USING THE SUBSTRATE BENCHMARK CLI VERSION 47.2.0
//! DATE: 2025-08-02, STEPS: `10`, REPEAT: `5`, LOW RANGE: `[]`, HIGH RANGE: `[]`
//! WORST CASE MAP SIZE: `1000000`
//! HOSTNAME: `toaster1`, CPU: `AMD Ryzen Threadripper 7980X 64-Cores`
//! WASM-EXECUTION: `Compiled`, CHAIN: `None`, DB CACHE: `1024`

// Executed Command:
// ./frame-omni-bencher
// v1
// benchmark
// pallet
// --runtime
// target/release/wbuild/people-rococo-runtime/people_rococo_runtime.compact.compressed.wasm
// --pallet
// pallet_people_multi
// --extrinsic
// *
// -r
// 5
// -s
// 10
// --template
// ../polkadot-sdk/./substrate/.maintain/frame-weight-template.hbs
// --output
// ../pallet_weight.rs

#![cfg_attr(rustfmt, rustfmt_skip)]
#![allow(unused_parens)]
#![allow(unused_imports)]
#![allow(missing_docs)]
#![allow(dead_code)]

use frame_support::{traits::Get, weights::{Weight, constants::RocksDbWeight}};
use core::marker::PhantomData;

/// Weight functions needed for `pallet_people_multi`.
pub trait WeightInfo {
	fn under_alias() -> Weight;
	fn set_alias_account() -> Weight;
	fn unset_alias_account() -> Weight;
	fn force_recognize_personhood(n: u32, ) -> Weight;
	fn set_personal_id_account() -> Weight;
	fn unset_personal_id_account() -> Weight;
	fn set_onboarding_size() -> Weight;
	fn merge_rings() -> Weight;
	fn migrate_included_key() -> Weight;
	fn migrate_onboarding_key() -> Weight;
	fn should_build_ring(n: u32, ) -> Weight;
	fn build_ring(n: u32, ) -> Weight;
	fn onboard_people() -> Weight;
	fn pending_suspensions_iteration() -> Weight;
	fn remove_suspended_keys(n: u32, ) -> Weight;
	fn migrate_keys_single_included_key() -> Weight;
	fn merge_queue_pages() -> Weight;
	fn on_poll_base() -> Weight;
	fn on_idle_base() -> Weight;
	fn as_person_alias_with_account() -> Weight;
	fn as_person_identity_with_account() -> Weight;
	fn as_person_alias_with_proof() -> Weight;
	fn as_person_identity_with_proof() -> Weight;
	fn as_person_alias_with_account_revised() -> Weight;
}

/// Weights for `pallet_people_multi` using the Substrate node and recommended hardware.
pub struct SubstrateWeight<T>(PhantomData<T>);
impl<T: frame_system::Config> WeightInfo for SubstrateWeight<T> {
	/// Storage: `People::AccountToAlias` (r:1 w:0)
	/// Proof: `People::AccountToAlias` (`max_values`: None, `max_size`: Some(120), added: 2595, mode: `MaxEncodedLen`)
	/// Storage: `People::Root` (r:1 w:0)
	/// Proof: `People::Root` (`max_values`: None, `max_size`: Some(840), added: 3315, mode: `MaxEncodedLen`)
	fn under_alias() -> Weight {
		// Proof Size summary in bytes:
		//  Measured:  `1244`
		//  Estimated: `4305`
		// Minimum execution time: 5_137_182_000 picoseconds.
		Weight::from_parts(5_139_775_000, 4305)
			.saturating_add(T::DbWeight::get().reads(2_u64))
	}
	/// Storage: `People::AccountToPersonalId` (r:1 w:0)
	/// Proof: `People::AccountToPersonalId` (`max_values`: None, `max_size`: Some(56), added: 2531, mode: `MaxEncodedLen`)
	/// Storage: `People::AliasToAccount` (r:1 w:1)
	/// Proof: `People::AliasToAccount` (`max_values`: None, `max_size`: Some(112), added: 2587, mode: `MaxEncodedLen`)
	/// Storage: `People::AccountToAlias` (r:2 w:2)
	/// Proof: `People::AccountToAlias` (`max_values`: None, `max_size`: Some(120), added: 2595, mode: `MaxEncodedLen`)
	/// Storage: `System::Account` (r:2 w:2)
	/// Proof: `System::Account` (`max_values`: None, `max_size`: Some(128), added: 2603, mode: `MaxEncodedLen`)
	fn set_alias_account() -> Weight {
		// Proof Size summary in bytes:
		//  Measured:  `745`
		//  Estimated: `6196`
		// Minimum execution time: 26_370_000 picoseconds.
		Weight::from_parts(26_751_000, 6196)
			.saturating_add(T::DbWeight::get().reads(6_u64))
			.saturating_add(T::DbWeight::get().writes(5_u64))
	}
	/// Storage: `People::AliasToAccount` (r:1 w:1)
	/// Proof: `People::AliasToAccount` (`max_values`: None, `max_size`: Some(112), added: 2587, mode: `MaxEncodedLen`)
	/// Storage: `System::Account` (r:1 w:1)
	/// Proof: `System::Account` (`max_values`: None, `max_size`: Some(128), added: 2603, mode: `MaxEncodedLen`)
	/// Storage: `People::AccountToAlias` (r:0 w:1)
	/// Proof: `People::AccountToAlias` (`max_values`: None, `max_size`: Some(120), added: 2595, mode: `MaxEncodedLen`)
	fn unset_alias_account() -> Weight {
		// Proof Size summary in bytes:
		//  Measured:  `576`
		//  Estimated: `3593`
		// Minimum execution time: 14_742_000 picoseconds.
		Weight::from_parts(15_934_000, 3593)
			.saturating_add(T::DbWeight::get().reads(2_u64))
			.saturating_add(T::DbWeight::get().writes(3_u64))
	}
	/// Storage: `People::NextPersonalId` (r:1 w:1)
	/// Proof: `People::NextPersonalId` (`max_values`: Some(1), `max_size`: Some(8), added: 503, mode: `MaxEncodedLen`)
	/// Storage: `People::Keys` (r:20 w:20)
	/// Proof: `People::Keys` (`max_values`: None, `max_size`: Some(56), added: 2531, mode: `MaxEncodedLen`)
	/// Storage: `People::QueuePageIndices` (r:1 w:1)
	/// Proof: `People::QueuePageIndices` (`max_values`: Some(1), `max_size`: Some(8), added: 503, mode: `MaxEncodedLen`)
	/// Storage: `People::OnboardingQueue` (r:1 w:1)
	/// Proof: `People::OnboardingQueue` (`max_values`: None, `max_size`: Some(973), added: 3448, mode: `MaxEncodedLen`)
	/// Storage: `People::CounterForKeys` (r:1 w:1)
	/// Proof: `People::CounterForKeys` (`max_values`: Some(1), `max_size`: Some(4), added: 499, mode: `MaxEncodedLen`)
	/// Storage: `People::People` (r:0 w:20)
	/// Proof: `People::People` (`max_values`: None, `max_size`: Some(99), added: 2574, mode: `MaxEncodedLen`)
	/// Storage: `People::ReservedPersonalId` (r:0 w:20)
	/// Proof: `People::ReservedPersonalId` (`max_values`: None, `max_size`: Some(16), added: 2491, mode: `MaxEncodedLen`)
	/// The range of component `n` is `[1, 20]`.
	fn force_recognize_personhood(n: u32, ) -> Weight {
		// Proof Size summary in bytes:
		//  Measured:  `190`
		//  Estimated: `4438 + n * (2531 ±0)`
		// Minimum execution time: 15_384_000 picoseconds.
		Weight::from_parts(5_630_460, 4438)
			// Standard Error: 61_038
			.saturating_add(Weight::from_parts(9_313_726, 0).saturating_mul(n.into()))
			.saturating_add(T::DbWeight::get().reads(4_u64))
			.saturating_add(T::DbWeight::get().reads((1_u64).saturating_mul(n.into())))
			.saturating_add(T::DbWeight::get().writes(4_u64))
			.saturating_add(T::DbWeight::get().writes((3_u64).saturating_mul(n.into())))
			.saturating_add(Weight::from_parts(0, 2531).saturating_mul(n.into()))
	}
	/// Storage: `People::AccountToPersonalId` (r:1 w:2)
	/// Proof: `People::AccountToPersonalId` (`max_values`: None, `max_size`: Some(56), added: 2531, mode: `MaxEncodedLen`)
	/// Storage: `People::AccountToAlias` (r:1 w:0)
	/// Proof: `People::AccountToAlias` (`max_values`: None, `max_size`: Some(120), added: 2595, mode: `MaxEncodedLen`)
	/// Storage: `People::People` (r:1 w:1)
	/// Proof: `People::People` (`max_values`: None, `max_size`: Some(99), added: 2574, mode: `MaxEncodedLen`)
	/// Storage: `System::Account` (r:2 w:2)
	/// Proof: `System::Account` (`max_values`: None, `max_size`: Some(128), added: 2603, mode: `MaxEncodedLen`)
	fn set_personal_id_account() -> Weight {
		// Proof Size summary in bytes:
		//  Measured:  `965`
		//  Estimated: `6196`
		// Minimum execution time: 24_757_000 picoseconds.
		Weight::from_parts(25_519_000, 6196)
			.saturating_add(T::DbWeight::get().reads(5_u64))
			.saturating_add(T::DbWeight::get().writes(5_u64))
	}
	/// Storage: `People::People` (r:1 w:1)
	/// Proof: `People::People` (`max_values`: None, `max_size`: Some(99), added: 2574, mode: `MaxEncodedLen`)
	/// Storage: `People::AccountToPersonalId` (r:1 w:1)
	/// Proof: `People::AccountToPersonalId` (`max_values`: None, `max_size`: Some(56), added: 2531, mode: `MaxEncodedLen`)
	/// Storage: `System::Account` (r:1 w:1)
	/// Proof: `System::Account` (`max_values`: None, `max_size`: Some(128), added: 2603, mode: `MaxEncodedLen`)
	fn unset_personal_id_account() -> Weight {
		// Proof Size summary in bytes:
		//  Measured:  `965`
		//  Estimated: `3593`
		// Minimum execution time: 18_829_000 picoseconds.
		Weight::from_parts(19_319_000, 3593)
			.saturating_add(T::DbWeight::get().reads(3_u64))
			.saturating_add(T::DbWeight::get().writes(3_u64))
	}
	/// Storage: `People::OnboardingSize` (r:0 w:1)
	/// Proof: `People::OnboardingSize` (`max_values`: Some(1), `max_size`: Some(4), added: 499, mode: `MaxEncodedLen`)
	fn set_onboarding_size() -> Weight {
		// Proof Size summary in bytes:
		//  Measured:  `0`
		//  Estimated: `0`
		// Minimum execution time: 1_392_000 picoseconds.
		Weight::from_parts(1_642_000, 0)
			.saturating_add(T::DbWeight::get().writes(1_u64))
	}
	/// Storage: `People::RingsState` (r:1 w:0)
	/// Proof: `People::RingsState` (`max_values`: Some(1), `max_size`: Some(2), added: 497, mode: `MaxEncodedLen`)
	/// Storage: `People::CurrentRingIndex` (r:1 w:0)
	/// Proof: `People::CurrentRingIndex` (`max_values`: Some(1), `max_size`: Some(4), added: 499, mode: `MaxEncodedLen`)
	/// Storage: `People::RingKeys` (r:2 w:2)
	/// Proof: `People::RingKeys` (`max_values`: None, `max_size`: Some(661), added: 3136, mode: `MaxEncodedLen`)
	/// Storage: `People::RingKeysStatus` (r:1 w:2)
	/// Proof: `People::RingKeysStatus` (`max_values`: None, `max_size`: Some(28), added: 2503, mode: `MaxEncodedLen`)
	/// Storage: `People::PendingSuspensions` (r:2 w:0)
	/// Proof: `People::PendingSuspensions` (`max_values`: None, `max_size`: Some(93), added: 2568, mode: `MaxEncodedLen`)
	/// Storage: `People::Keys` (r:8 w:0)
	/// Proof: `People::Keys` (`max_values`: None, `max_size`: Some(56), added: 2531, mode: `MaxEncodedLen`)
	/// Storage: `People::People` (r:8 w:8)
	/// Proof: `People::People` (`max_values`: None, `max_size`: Some(99), added: 2574, mode: `MaxEncodedLen`)
	/// Storage: `People::Root` (r:0 w:1)
	/// Proof: `People::Root` (`max_values`: None, `max_size`: Some(840), added: 3315, mode: `MaxEncodedLen`)
	fn merge_rings() -> Weight {
		// Proof Size summary in bytes:
		//  Measured:  `3496`
		//  Estimated: `21582`
		// Minimum execution time: 84_919_000 picoseconds.
		Weight::from_parts(86_712_000, 21582)
			.saturating_add(T::DbWeight::get().reads(23_u64))
			.saturating_add(T::DbWeight::get().writes(13_u64))
	}
	/// Storage: `People::Keys` (r:2 w:2)
	/// Proof: `People::Keys` (`max_values`: None, `max_size`: Some(56), added: 2531, mode: `MaxEncodedLen`)
	/// Storage: `People::People` (r:1 w:1)
	/// Proof: `People::People` (`max_values`: None, `max_size`: Some(99), added: 2574, mode: `MaxEncodedLen`)
	/// Storage: `People::KeyMigrationQueue` (r:1 w:1)
	/// Proof: `People::KeyMigrationQueue` (`max_values`: None, `max_size`: Some(56), added: 2531, mode: `MaxEncodedLen`)
	/// Storage: `People::CounterForKeys` (r:1 w:1)
	/// Proof: `People::CounterForKeys` (`max_values`: Some(1), `max_size`: Some(4), added: 499, mode: `MaxEncodedLen`)
	fn migrate_included_key() -> Weight {
		// Proof Size summary in bytes:
		//  Measured:  `1233`
		//  Estimated: `6052`
		// Minimum execution time: 25_118_000 picoseconds.
		Weight::from_parts(25_559_000, 6052)
			.saturating_add(T::DbWeight::get().reads(5_u64))
			.saturating_add(T::DbWeight::get().writes(5_u64))
	}
	/// Storage: `People::Keys` (r:2 w:2)
	/// Proof: `People::Keys` (`max_values`: None, `max_size`: Some(56), added: 2531, mode: `MaxEncodedLen`)
	/// Storage: `People::People` (r:1 w:1)
	/// Proof: `People::People` (`max_values`: None, `max_size`: Some(99), added: 2574, mode: `MaxEncodedLen`)
	/// Storage: `People::OnboardingQueue` (r:1 w:1)
	/// Proof: `People::OnboardingQueue` (`max_values`: None, `max_size`: Some(973), added: 3448, mode: `MaxEncodedLen`)
	/// Storage: `People::CounterForKeys` (r:1 w:1)
	/// Proof: `People::CounterForKeys` (`max_values`: Some(1), `max_size`: Some(4), added: 499, mode: `MaxEncodedLen`)
	fn migrate_onboarding_key() -> Weight {
		// Proof Size summary in bytes:
		//  Measured:  `1344`
		//  Estimated: `6052`
		// Minimum execution time: 26_500_000 picoseconds.
		Weight::from_parts(26_761_000, 6052)
			.saturating_add(T::DbWeight::get().reads(5_u64))
			.saturating_add(T::DbWeight::get().writes(5_u64))
	}
	/// Storage: `People::RingsState` (r:1 w:0)
	/// Proof: `People::RingsState` (`max_values`: Some(1), `max_size`: Some(2), added: 497, mode: `MaxEncodedLen`)
	/// Storage: `People::PendingSuspensions` (r:1 w:0)
	/// Proof: `People::PendingSuspensions` (`max_values`: None, `max_size`: Some(93), added: 2568, mode: `MaxEncodedLen`)
	/// Storage: `People::RingKeysStatus` (r:1 w:0)
	/// Proof: `People::RingKeysStatus` (`max_values`: None, `max_size`: Some(28), added: 2503, mode: `MaxEncodedLen`)
	/// The range of component `n` is `[1, 20]`.
	fn should_build_ring(_n: u32, ) -> Weight {
		// Proof Size summary in bytes:
		//  Measured:  `277`
		//  Estimated: `3558`
		// Minimum execution time: 7_662_000 picoseconds.
		Weight::from_parts(7_967_812, 3558)
			.saturating_add(T::DbWeight::get().reads(3_u64))
	}
	/// Storage: `People::RingKeys` (r:1 w:0)
	/// Proof: `People::RingKeys` (`max_values`: None, `max_size`: Some(661), added: 3136, mode: `MaxEncodedLen`)
	/// Storage: `People::RingKeysStatus` (r:1 w:1)
	/// Proof: `People::RingKeysStatus` (`max_values`: None, `max_size`: Some(28), added: 2503, mode: `MaxEncodedLen`)
	/// Storage: `People::Root` (r:1 w:1)
	/// Proof: `People::Root` (`max_values`: None, `max_size`: Some(840), added: 3315, mode: `MaxEncodedLen`)
	/// Storage: `People::Chunks` (r:1 w:0)
	/// Proof: `People::Chunks` (`max_values`: None, `max_size`: Some(6158), added: 8633, mode: `MaxEncodedLen`)
	/// The range of component `n` is `[1, 20]`.
	fn build_ring(n: u32, ) -> Weight {
		// Proof Size summary in bytes:
		//  Measured:  `7314`
		//  Estimated: `9623`
		// Minimum execution time: 42_484_802_000 picoseconds.
		Weight::from_parts(42_550_136_386, 9623)
			// Standard Error: 8_484_541
			.saturating_add(Weight::from_parts(652_712_146, 0).saturating_mul(n.into()))
			.saturating_add(T::DbWeight::get().reads(4_u64))
			.saturating_add(T::DbWeight::get().writes(2_u64))
	}
	/// Storage: `People::CurrentRingIndex` (r:1 w:1)
	/// Proof: `People::CurrentRingIndex` (`max_values`: Some(1), `max_size`: Some(4), added: 499, mode: `MaxEncodedLen`)
	/// Storage: `People::RingKeys` (r:1 w:1)
	/// Proof: `People::RingKeys` (`max_values`: None, `max_size`: Some(661), added: 3136, mode: `MaxEncodedLen`)
	/// Storage: `People::RingKeysStatus` (r:1 w:1)
	/// Proof: `People::RingKeysStatus` (`max_values`: None, `max_size`: Some(28), added: 2503, mode: `MaxEncodedLen`)
	/// Storage: `People::QueuePageIndices` (r:1 w:1)
	/// Proof: `People::QueuePageIndices` (`max_values`: Some(1), `max_size`: Some(8), added: 503, mode: `MaxEncodedLen`)
	/// Storage: `People::OnboardingQueue` (r:2 w:2)
	/// Proof: `People::OnboardingQueue` (`max_values`: None, `max_size`: Some(973), added: 3448, mode: `MaxEncodedLen`)
	/// Storage: `People::OnboardingSize` (r:1 w:0)
	/// Proof: `People::OnboardingSize` (`max_values`: Some(1), `max_size`: Some(4), added: 499, mode: `MaxEncodedLen`)
	/// Storage: `People::RingsState` (r:1 w:0)
	/// Proof: `People::RingsState` (`max_values`: Some(1), `max_size`: Some(2), added: 497, mode: `MaxEncodedLen`)
	/// Storage: `People::PendingSuspensions` (r:1 w:0)
	/// Proof: `People::PendingSuspensions` (`max_values`: None, `max_size`: Some(93), added: 2568, mode: `MaxEncodedLen`)
	/// Storage: `People::Keys` (r:20 w:0)
	/// Proof: `People::Keys` (`max_values`: None, `max_size`: Some(56), added: 2531, mode: `MaxEncodedLen`)
	/// Storage: `People::People` (r:20 w:20)
	/// Proof: `People::People` (`max_values`: None, `max_size`: Some(99), added: 2574, mode: `MaxEncodedLen`)
	/// Storage: `People::ActiveMembers` (r:1 w:1)
	/// Proof: `People::ActiveMembers` (`max_values`: Some(1), `max_size`: Some(4), added: 499, mode: `MaxEncodedLen`)
	fn onboard_people() -> Weight {
		// Proof Size summary in bytes:
		//  Measured:  `6606`
		//  Estimated: `52470`
		// Minimum execution time: 164_330_000 picoseconds.
		Weight::from_parts(166_012_000, 52470)
			.saturating_add(T::DbWeight::get().reads(50_u64))
			.saturating_add(T::DbWeight::get().writes(27_u64))
	}
	/// Storage: `People::PendingSuspensions` (r:1 w:0)
	/// Proof: `People::PendingSuspensions` (`max_values`: None, `max_size`: Some(93), added: 2568, mode: `MaxEncodedLen`)
	fn pending_suspensions_iteration() -> Weight {
		// Proof Size summary in bytes:
		//  Measured:  `378`
		//  Estimated: `3558`
		// Minimum execution time: 3_305_000 picoseconds.
		Weight::from_parts(3_365_000, 3558)
			.saturating_add(T::DbWeight::get().reads(1_u64))
	}
	/// Storage: `People::RingKeys` (r:1 w:1)
	/// Proof: `People::RingKeys` (`max_values`: None, `max_size`: Some(661), added: 3136, mode: `MaxEncodedLen`)
	/// Storage: `People::PendingSuspensions` (r:1 w:1)
	/// Proof: `People::PendingSuspensions` (`max_values`: None, `max_size`: Some(93), added: 2568, mode: `MaxEncodedLen`)
	/// Storage: `People::RingKeysStatus` (r:1 w:1)
	/// Proof: `People::RingKeysStatus` (`max_values`: None, `max_size`: Some(28), added: 2503, mode: `MaxEncodedLen`)
	/// Storage: `People::ActiveMembers` (r:1 w:1)
	/// Proof: `People::ActiveMembers` (`max_values`: Some(1), `max_size`: Some(4), added: 499, mode: `MaxEncodedLen`)
	/// Storage: `People::Root` (r:1 w:1)
	/// Proof: `People::Root` (`max_values`: None, `max_size`: Some(840), added: 3315, mode: `MaxEncodedLen`)
	/// The range of component `n` is `[1, 20]`.
	fn remove_suspended_keys(n: u32, ) -> Weight {
		// Proof Size summary in bytes:
		//  Measured:  `1955 + n * (4 ±0)`
		//  Estimated: `4305`
		// Minimum execution time: 5_132_935_000 picoseconds.
		Weight::from_parts(5_131_745_324, 4305)
			// Standard Error: 909_536
			.saturating_add(Weight::from_parts(2_227_614, 0).saturating_mul(n.into()))
			.saturating_add(T::DbWeight::get().reads(5_u64))
			.saturating_add(T::DbWeight::get().writes(5_u64))
	}
	/// Storage: `People::People` (r:1 w:1)
	/// Proof: `People::People` (`max_values`: None, `max_size`: Some(99), added: 2574, mode: `MaxEncodedLen`)
	/// Storage: `People::PendingSuspensions` (r:1 w:1)
	/// Proof: `People::PendingSuspensions` (`max_values`: None, `max_size`: Some(93), added: 2568, mode: `MaxEncodedLen`)
	/// Storage: `People::Keys` (r:2 w:2)
	/// Proof: `People::Keys` (`max_values`: None, `max_size`: Some(56), added: 2531, mode: `MaxEncodedLen`)
	/// Storage: `People::CounterForKeys` (r:1 w:1)
	/// Proof: `People::CounterForKeys` (`max_values`: Some(1), `max_size`: Some(4), added: 499, mode: `MaxEncodedLen`)
	/// Storage: `People::QueuePageIndices` (r:1 w:1)
	/// Proof: `People::QueuePageIndices` (`max_values`: Some(1), `max_size`: Some(8), added: 503, mode: `MaxEncodedLen`)
	/// Storage: `People::OnboardingQueue` (r:1 w:1)
	/// Proof: `People::OnboardingQueue` (`max_values`: None, `max_size`: Some(973), added: 3448, mode: `MaxEncodedLen`)
	fn migrate_keys_single_included_key() -> Weight {
		// Proof Size summary in bytes:
		//  Measured:  `1599`
		//  Estimated: `6052`
		// Minimum execution time: 29_265_000 picoseconds.
		Weight::from_parts(30_246_000, 6052)
			.saturating_add(T::DbWeight::get().reads(7_u64))
			.saturating_add(T::DbWeight::get().writes(7_u64))
	}
	/// Storage: `People::Keys` (r:29 w:0)
	/// Proof: `People::Keys` (`max_values`: None, `max_size`: Some(56), added: 2531, mode: `MaxEncodedLen`)
	/// Storage: `People::People` (r:29 w:29)
	/// Proof: `People::People` (`max_values`: None, `max_size`: Some(99), added: 2574, mode: `MaxEncodedLen`)
	/// Storage: `People::QueuePageIndices` (r:1 w:1)
	/// Proof: `People::QueuePageIndices` (`max_values`: Some(1), `max_size`: Some(8), added: 503, mode: `MaxEncodedLen`)
	/// Storage: `People::OnboardingQueue` (r:0 w:2)
	/// Proof: `People::OnboardingQueue` (`max_values`: None, `max_size`: Some(973), added: 3448, mode: `MaxEncodedLen`)
	fn merge_queue_pages() -> Weight {
		// Proof Size summary in bytes:
		//  Measured:  `4158`
		//  Estimated: `75636`
		// Minimum execution time: 176_828_000 picoseconds.
		Weight::from_parts(180_284_000, 75636)
			.saturating_add(T::DbWeight::get().reads(59_u64))
			.saturating_add(T::DbWeight::get().writes(32_u64))
	}
	/// Storage: `People::RingsState` (r:1 w:0)
	/// Proof: `People::RingsState` (`max_values`: Some(1), `max_size`: Some(2), added: 497, mode: `MaxEncodedLen`)
	/// Storage: `People::PendingSuspensions` (r:1 w:0)
	/// Proof: `People::PendingSuspensions` (`max_values`: None, `max_size`: Some(93), added: 2568, mode: `MaxEncodedLen`)
	/// Storage: `People::QueuePageIndices` (r:1 w:0)
	/// Proof: `People::QueuePageIndices` (`max_values`: Some(1), `max_size`: Some(8), added: 503, mode: `MaxEncodedLen`)
	/// Storage: `People::OnboardingQueue` (r:2 w:0)
	/// Proof: `People::OnboardingQueue` (`max_values`: None, `max_size`: Some(973), added: 3448, mode: `MaxEncodedLen`)
	fn on_poll_base() -> Weight {
		// Proof Size summary in bytes:
		//  Measured:  `1278`
		//  Estimated: `7886`
		// Minimum execution time: 12_389_000 picoseconds.
		Weight::from_parts(12_529_000, 7886)
			.saturating_add(T::DbWeight::get().reads(5_u64))
	}
	/// Storage: `People::RingsState` (r:1 w:0)
	/// Proof: `People::RingsState` (`max_values`: Some(1), `max_size`: Some(2), added: 497, mode: `MaxEncodedLen`)
	/// Storage: `People::PendingSuspensions` (r:3 w:0)
	/// Proof: `People::PendingSuspensions` (`max_values`: None, `max_size`: Some(93), added: 2568, mode: `MaxEncodedLen`)
	/// Storage: `People::CurrentRingIndex` (r:1 w:0)
	/// Proof: `People::CurrentRingIndex` (`max_values`: Some(1), `max_size`: Some(4), added: 499, mode: `MaxEncodedLen`)
	/// Storage: `People::RingKeys` (r:1 w:0)
	/// Proof: `People::RingKeys` (`max_values`: None, `max_size`: Some(661), added: 3136, mode: `MaxEncodedLen`)
	/// Storage: `People::RingKeysStatus` (r:2 w:0)
	/// Proof: `People::RingKeysStatus` (`max_values`: None, `max_size`: Some(28), added: 2503, mode: `MaxEncodedLen`)
	/// Storage: `People::QueuePageIndices` (r:1 w:0)
	/// Proof: `People::QueuePageIndices` (`max_values`: Some(1), `max_size`: Some(8), added: 503, mode: `MaxEncodedLen`)
	/// Storage: `People::OnboardingQueue` (r:2 w:0)
	/// Proof: `People::OnboardingQueue` (`max_values`: None, `max_size`: Some(973), added: 3448, mode: `MaxEncodedLen`)
	/// Storage: `People::OnboardingSize` (r:1 w:0)
	/// Proof: `People::OnboardingSize` (`max_values`: Some(1), `max_size`: Some(4), added: 499, mode: `MaxEncodedLen`)
	fn on_idle_base() -> Weight {
		// Proof Size summary in bytes:
		//  Measured:  `818`
		//  Estimated: `8694`
		// Minimum execution time: 30_907_000 picoseconds.
		Weight::from_parts(31_628_000, 8694)
			.saturating_add(T::DbWeight::get().reads(12_u64))
	}
	/// Storage: `People::AccountToAlias` (r:1 w:0)
	/// Proof: `People::AccountToAlias` (`max_values`: None, `max_size`: Some(120), added: 2595, mode: `MaxEncodedLen`)
	/// Storage: `People::Root` (r:1 w:0)
	/// Proof: `People::Root` (`max_values`: None, `max_size`: Some(840), added: 3315, mode: `MaxEncodedLen`)
	/// Storage: `System::Account` (r:1 w:1)
	/// Proof: `System::Account` (`max_values`: None, `max_size`: Some(128), added: 2603, mode: `MaxEncodedLen`)
	fn as_person_alias_with_account() -> Weight {
		// Proof Size summary in bytes:
		//  Measured:  `1345`
		//  Estimated: `4305`
		// Minimum execution time: 5_190_694_000 picoseconds.
		Weight::from_parts(5_196_672_000, 4305)
			.saturating_add(T::DbWeight::get().reads(3_u64))
			.saturating_add(T::DbWeight::get().writes(1_u64))
	}
	/// Storage: `People::AccountToPersonalId` (r:1 w:0)
	/// Proof: `People::AccountToPersonalId` (`max_values`: None, `max_size`: Some(56), added: 2531, mode: `MaxEncodedLen`)
	/// Storage: `System::Account` (r:1 w:1)
	/// Proof: `System::Account` (`max_values`: None, `max_size`: Some(128), added: 2603, mode: `MaxEncodedLen`)
	fn as_person_identity_with_account() -> Weight {
		// Proof Size summary in bytes:
		//  Measured:  `505`
		//  Estimated: `3593`
		// Minimum execution time: 12_960_000 picoseconds.
		Weight::from_parts(13_301_000, 3593)
			.saturating_add(T::DbWeight::get().reads(2_u64))
			.saturating_add(T::DbWeight::get().writes(1_u64))
	}
	/// Storage: `People::Root` (r:1 w:0)
	/// Proof: `People::Root` (`max_values`: None, `max_size`: Some(840), added: 3315, mode: `MaxEncodedLen`)
	/// Storage: `People::AccountToAlias` (r:1 w:0)
	/// Proof: `People::AccountToAlias` (`max_values`: None, `max_size`: Some(120), added: 2595, mode: `MaxEncodedLen`)
	fn as_person_alias_with_proof() -> Weight {
		// Proof Size summary in bytes:
		//  Measured:  `1099`
		//  Estimated: `4305`
		// Minimum execution time: 25_167_913_000 picoseconds.
		Weight::from_parts(25_204_118_000, 4305)
			.saturating_add(T::DbWeight::get().reads(2_u64))
	}
	/// Storage: `People::People` (r:1 w:0)
	/// Proof: `People::People` (`max_values`: None, `max_size`: Some(99), added: 2574, mode: `MaxEncodedLen`)
	fn as_person_identity_with_proof() -> Weight {
		// Proof Size summary in bytes:
		//  Measured:  `754`
		//  Estimated: `3564`
		// Minimum execution time: 1_603_745_000 picoseconds.
		Weight::from_parts(1_606_019_000, 3564)
			.saturating_add(T::DbWeight::get().reads(1_u64))
	}
	/// Storage: `People::AccountToAlias` (r:1 w:1)
	/// Proof: `People::AccountToAlias` (`max_values`: None, `max_size`: Some(120), added: 2595, mode: `MaxEncodedLen`)
	/// Storage: `People::Root` (r:1 w:0)
	/// Proof: `People::Root` (`max_values`: None, `max_size`: Some(840), added: 3315, mode: `MaxEncodedLen`)
	/// Storage: `System::Account` (r:1 w:1)
	/// Proof: `System::Account` (`max_values`: None, `max_size`: Some(128), added: 2603, mode: `MaxEncodedLen`)
	fn as_person_alias_with_account_revised() -> Weight {
		// Proof Size summary in bytes:
		//  Measured:  `1345`
		//  Estimated: `4305`
		// Minimum execution time: 25_323_961_000 picoseconds.
		Weight::from_parts(25_367_206_000, 4305)
			.saturating_add(T::DbWeight::get().reads(3_u64))
			.saturating_add(T::DbWeight::get().writes(2_u64))
	}
}

// For backwards compatibility and tests.
impl WeightInfo for () {
	/// Storage: `People::AccountToAlias` (r:1 w:0)
	/// Proof: `People::AccountToAlias` (`max_values`: None, `max_size`: Some(120), added: 2595, mode: `MaxEncodedLen`)
	/// Storage: `People::Root` (r:1 w:0)
	/// Proof: `People::Root` (`max_values`: None, `max_size`: Some(840), added: 3315, mode: `MaxEncodedLen`)
	fn under_alias() -> Weight {
		// Proof Size summary in bytes:
		//  Measured:  `1244`
		//  Estimated: `4305`
		// Minimum execution time: 5_137_182_000 picoseconds.
		Weight::from_parts(5_139_775_000, 4305)
			.saturating_add(RocksDbWeight::get().reads(2_u64))
	}
	/// Storage: `People::AccountToPersonalId` (r:1 w:0)
	/// Proof: `People::AccountToPersonalId` (`max_values`: None, `max_size`: Some(56), added: 2531, mode: `MaxEncodedLen`)
	/// Storage: `People::AliasToAccount` (r:1 w:1)
	/// Proof: `People::AliasToAccount` (`max_values`: None, `max_size`: Some(112), added: 2587, mode: `MaxEncodedLen`)
	/// Storage: `People::AccountToAlias` (r:2 w:2)
	/// Proof: `People::AccountToAlias` (`max_values`: None, `max_size`: Some(120), added: 2595, mode: `MaxEncodedLen`)
	/// Storage: `System::Account` (r:2 w:2)
	/// Proof: `System::Account` (`max_values`: None, `max_size`: Some(128), added: 2603, mode: `MaxEncodedLen`)
	fn set_alias_account() -> Weight {
		// Proof Size summary in bytes:
		//  Measured:  `745`
		//  Estimated: `6196`
		// Minimum execution time: 26_370_000 picoseconds.
		Weight::from_parts(26_751_000, 6196)
			.saturating_add(RocksDbWeight::get().reads(6_u64))
			.saturating_add(RocksDbWeight::get().writes(5_u64))
	}
	/// Storage: `People::AliasToAccount` (r:1 w:1)
	/// Proof: `People::AliasToAccount` (`max_values`: None, `max_size`: Some(112), added: 2587, mode: `MaxEncodedLen`)
	/// Storage: `System::Account` (r:1 w:1)
	/// Proof: `System::Account` (`max_values`: None, `max_size`: Some(128), added: 2603, mode: `MaxEncodedLen`)
	/// Storage: `People::AccountToAlias` (r:0 w:1)
	/// Proof: `People::AccountToAlias` (`max_values`: None, `max_size`: Some(120), added: 2595, mode: `MaxEncodedLen`)
	fn unset_alias_account() -> Weight {
		// Proof Size summary in bytes:
		//  Measured:  `576`
		//  Estimated: `3593`
		// Minimum execution time: 14_742_000 picoseconds.
		Weight::from_parts(15_934_000, 3593)
			.saturating_add(RocksDbWeight::get().reads(2_u64))
			.saturating_add(RocksDbWeight::get().writes(3_u64))
	}
	/// Storage: `People::NextPersonalId` (r:1 w:1)
	/// Proof: `People::NextPersonalId` (`max_values`: Some(1), `max_size`: Some(8), added: 503, mode: `MaxEncodedLen`)
	/// Storage: `People::Keys` (r:20 w:20)
	/// Proof: `People::Keys` (`max_values`: None, `max_size`: Some(56), added: 2531, mode: `MaxEncodedLen`)
	/// Storage: `People::QueuePageIndices` (r:1 w:1)
	/// Proof: `People::QueuePageIndices` (`max_values`: Some(1), `max_size`: Some(8), added: 503, mode: `MaxEncodedLen`)
	/// Storage: `People::OnboardingQueue` (r:1 w:1)
	/// Proof: `People::OnboardingQueue` (`max_values`: None, `max_size`: Some(973), added: 3448, mode: `MaxEncodedLen`)
	/// Storage: `People::CounterForKeys` (r:1 w:1)
	/// Proof: `People::CounterForKeys` (`max_values`: Some(1), `max_size`: Some(4), added: 499, mode: `MaxEncodedLen`)
	/// Storage: `People::People` (r:0 w:20)
	/// Proof: `People::People` (`max_values`: None, `max_size`: Some(99), added: 2574, mode: `MaxEncodedLen`)
	/// Storage: `People::ReservedPersonalId` (r:0 w:20)
	/// Proof: `People::ReservedPersonalId` (`max_values`: None, `max_size`: Some(16), added: 2491, mode: `MaxEncodedLen`)
	/// The range of component `n` is `[1, 20]`.
	fn force_recognize_personhood(n: u32, ) -> Weight {
		// Proof Size summary in bytes:
		//  Measured:  `190`
		//  Estimated: `4438 + n * (2531 ±0)`
		// Minimum execution time: 15_384_000 picoseconds.
		Weight::from_parts(5_630_460, 4438)
			// Standard Error: 61_038
			.saturating_add(Weight::from_parts(9_313_726, 0).saturating_mul(n.into()))
			.saturating_add(RocksDbWeight::get().reads(4_u64))
			.saturating_add(RocksDbWeight::get().reads((1_u64).saturating_mul(n.into())))
			.saturating_add(RocksDbWeight::get().writes(4_u64))
			.saturating_add(RocksDbWeight::get().writes((3_u64).saturating_mul(n.into())))
			.saturating_add(Weight::from_parts(0, 2531).saturating_mul(n.into()))
	}
	/// Storage: `People::AccountToPersonalId` (r:1 w:2)
	/// Proof: `People::AccountToPersonalId` (`max_values`: None, `max_size`: Some(56), added: 2531, mode: `MaxEncodedLen`)
	/// Storage: `People::AccountToAlias` (r:1 w:0)
	/// Proof: `People::AccountToAlias` (`max_values`: None, `max_size`: Some(120), added: 2595, mode: `MaxEncodedLen`)
	/// Storage: `People::People` (r:1 w:1)
	/// Proof: `People::People` (`max_values`: None, `max_size`: Some(99), added: 2574, mode: `MaxEncodedLen`)
	/// Storage: `System::Account` (r:2 w:2)
	/// Proof: `System::Account` (`max_values`: None, `max_size`: Some(128), added: 2603, mode: `MaxEncodedLen`)
	fn set_personal_id_account() -> Weight {
		// Proof Size summary in bytes:
		//  Measured:  `965`
		//  Estimated: `6196`
		// Minimum execution time: 24_757_000 picoseconds.
		Weight::from_parts(25_519_000, 6196)
			.saturating_add(RocksDbWeight::get().reads(5_u64))
			.saturating_add(RocksDbWeight::get().writes(5_u64))
	}
	/// Storage: `People::People` (r:1 w:1)
	/// Proof: `People::People` (`max_values`: None, `max_size`: Some(99), added: 2574, mode: `MaxEncodedLen`)
	/// Storage: `People::AccountToPersonalId` (r:1 w:1)
	/// Proof: `People::AccountToPersonalId` (`max_values`: None, `max_size`: Some(56), added: 2531, mode: `MaxEncodedLen`)
	/// Storage: `System::Account` (r:1 w:1)
	/// Proof: `System::Account` (`max_values`: None, `max_size`: Some(128), added: 2603, mode: `MaxEncodedLen`)
	fn unset_personal_id_account() -> Weight {
		// Proof Size summary in bytes:
		//  Measured:  `965`
		//  Estimated: `3593`
		// Minimum execution time: 18_829_000 picoseconds.
		Weight::from_parts(19_319_000, 3593)
			.saturating_add(RocksDbWeight::get().reads(3_u64))
			.saturating_add(RocksDbWeight::get().writes(3_u64))
	}
	/// Storage: `People::OnboardingSize` (r:0 w:1)
	/// Proof: `People::OnboardingSize` (`max_values`: Some(1), `max_size`: Some(4), added: 499, mode: `MaxEncodedLen`)
	fn set_onboarding_size() -> Weight {
		// Proof Size summary in bytes:
		//  Measured:  `0`
		//  Estimated: `0`
		// Minimum execution time: 1_392_000 picoseconds.
		Weight::from_parts(1_642_000, 0)
			.saturating_add(RocksDbWeight::get().writes(1_u64))
	}
	/// Storage: `People::RingsState` (r:1 w:0)
	/// Proof: `People::RingsState` (`max_values`: Some(1), `max_size`: Some(2), added: 497, mode: `MaxEncodedLen`)
	/// Storage: `People::CurrentRingIndex` (r:1 w:0)
	/// Proof: `People::CurrentRingIndex` (`max_values`: Some(1), `max_size`: Some(4), added: 499, mode: `MaxEncodedLen`)
	/// Storage: `People::RingKeys` (r:2 w:2)
	/// Proof: `People::RingKeys` (`max_values`: None, `max_size`: Some(661), added: 3136, mode: `MaxEncodedLen`)
	/// Storage: `People::RingKeysStatus` (r:1 w:2)
	/// Proof: `People::RingKeysStatus` (`max_values`: None, `max_size`: Some(28), added: 2503, mode: `MaxEncodedLen`)
	/// Storage: `People::PendingSuspensions` (r:2 w:0)
	/// Proof: `People::PendingSuspensions` (`max_values`: None, `max_size`: Some(93), added: 2568, mode: `MaxEncodedLen`)
	/// Storage: `People::Keys` (r:8 w:0)
	/// Proof: `People::Keys` (`max_values`: None, `max_size`: Some(56), added: 2531, mode: `MaxEncodedLen`)
	/// Storage: `People::People` (r:8 w:8)
	/// Proof: `People::People` (`max_values`: None, `max_size`: Some(99), added: 2574, mode: `MaxEncodedLen`)
	/// Storage: `People::Root` (r:0 w:1)
	/// Proof: `People::Root` (`max_values`: None, `max_size`: Some(840), added: 3315, mode: `MaxEncodedLen`)
	fn merge_rings() -> Weight {
		// Proof Size summary in bytes:
		//  Measured:  `3496`
		//  Estimated: `21582`
		// Minimum execution time: 84_919_000 picoseconds.
		Weight::from_parts(86_712_000, 21582)
			.saturating_add(RocksDbWeight::get().reads(23_u64))
			.saturating_add(RocksDbWeight::get().writes(13_u64))
	}
	/// Storage: `People::Keys` (r:2 w:2)
	/// Proof: `People::Keys` (`max_values`: None, `max_size`: Some(56), added: 2531, mode: `MaxEncodedLen`)
	/// Storage: `People::People` (r:1 w:1)
	/// Proof: `People::People` (`max_values`: None, `max_size`: Some(99), added: 2574, mode: `MaxEncodedLen`)
	/// Storage: `People::KeyMigrationQueue` (r:1 w:1)
	/// Proof: `People::KeyMigrationQueue` (`max_values`: None, `max_size`: Some(56), added: 2531, mode: `MaxEncodedLen`)
	/// Storage: `People::CounterForKeys` (r:1 w:1)
	/// Proof: `People::CounterForKeys` (`max_values`: Some(1), `max_size`: Some(4), added: 499, mode: `MaxEncodedLen`)
	fn migrate_included_key() -> Weight {
		// Proof Size summary in bytes:
		//  Measured:  `1233`
		//  Estimated: `6052`
		// Minimum execution time: 25_118_000 picoseconds.
		Weight::from_parts(25_559_000, 6052)
			.saturating_add(RocksDbWeight::get().reads(5_u64))
			.saturating_add(RocksDbWeight::get().writes(5_u64))
	}
	/// Storage: `People::Keys` (r:2 w:2)
	/// Proof: `People::Keys` (`max_values`: None, `max_size`: Some(56), added: 2531, mode: `MaxEncodedLen`)
	/// Storage: `People::People` (r:1 w:1)
	/// Proof: `People::People` (`max_values`: None, `max_size`: Some(99), added: 2574, mode: `MaxEncodedLen`)
	/// Storage: `People::OnboardingQueue` (r:1 w:1)
	/// Proof: `People::OnboardingQueue` (`max_values`: None, `max_size`: Some(973), added: 3448, mode: `MaxEncodedLen`)
	/// Storage: `People::CounterForKeys` (r:1 w:1)
	/// Proof: `People::CounterForKeys` (`max_values`: Some(1), `max_size`: Some(4), added: 499, mode: `MaxEncodedLen`)
	fn migrate_onboarding_key() -> Weight {
		// Proof Size summary in bytes:
		//  Measured:  `1344`
		//  Estimated: `6052`
		// Minimum execution time: 26_500_000 picoseconds.
		Weight::from_parts(26_761_000, 6052)
			.saturating_add(RocksDbWeight::get().reads(5_u64))
			.saturating_add(RocksDbWeight::get().writes(5_u64))
	}
	/// Storage: `People::RingsState` (r:1 w:0)
	/// Proof: `People::RingsState` (`max_values`: Some(1), `max_size`: Some(2), added: 497, mode: `MaxEncodedLen`)
	/// Storage: `People::PendingSuspensions` (r:1 w:0)
	/// Proof: `People::PendingSuspensions` (`max_values`: None, `max_size`: Some(93), added: 2568, mode: `MaxEncodedLen`)
	/// Storage: `People::RingKeysStatus` (r:1 w:0)
	/// Proof: `People::RingKeysStatus` (`max_values`: None, `max_size`: Some(28), added: 2503, mode: `MaxEncodedLen`)
	/// The range of component `n` is `[1, 20]`.
	fn should_build_ring(_n: u32, ) -> Weight {
		// Proof Size summary in bytes:
		//  Measured:  `277`
		//  Estimated: `3558`
		// Minimum execution time: 7_662_000 picoseconds.
		Weight::from_parts(7_967_812, 3558)
			.saturating_add(RocksDbWeight::get().reads(3_u64))
	}
	/// Storage: `People::RingKeys` (r:1 w:0)
	/// Proof: `People::RingKeys` (`max_values`: None, `max_size`: Some(661), added: 3136, mode: `MaxEncodedLen`)
	/// Storage: `People::RingKeysStatus` (r:1 w:1)
	/// Proof: `People::RingKeysStatus` (`max_values`: None, `max_size`: Some(28), added: 2503, mode: `MaxEncodedLen`)
	/// Storage: `People::Root` (r:1 w:1)
	/// Proof: `People::Root` (`max_values`: None, `max_size`: Some(840), added: 3315, mode: `MaxEncodedLen`)
	/// Storage: `People::Chunks` (r:1 w:0)
	/// Proof: `People::Chunks` (`max_values`: None, `max_size`: Some(6158), added: 8633, mode: `MaxEncodedLen`)
	/// The range of component `n` is `[1, 20]`.
	fn build_ring(n: u32, ) -> Weight {
		// Proof Size summary in bytes:
		//  Measured:  `7314`
		//  Estimated: `9623`
		// Minimum execution time: 42_484_802_000 picoseconds.
		Weight::from_parts(42_550_136_386, 9623)
			// Standard Error: 8_484_541
			.saturating_add(Weight::from_parts(652_712_146, 0).saturating_mul(n.into()))
			.saturating_add(RocksDbWeight::get().reads(4_u64))
			.saturating_add(RocksDbWeight::get().writes(2_u64))
	}
	/// Storage: `People::CurrentRingIndex` (r:1 w:1)
	/// Proof: `People::CurrentRingIndex` (`max_values`: Some(1), `max_size`: Some(4), added: 499, mode: `MaxEncodedLen`)
	/// Storage: `People::RingKeys` (r:1 w:1)
	/// Proof: `People::RingKeys` (`max_values`: None, `max_size`: Some(661), added: 3136, mode: `MaxEncodedLen`)
	/// Storage: `People::RingKeysStatus` (r:1 w:1)
	/// Proof: `People::RingKeysStatus` (`max_values`: None, `max_size`: Some(28), added: 2503, mode: `MaxEncodedLen`)
	/// Storage: `People::QueuePageIndices` (r:1 w:1)
	/// Proof: `People::QueuePageIndices` (`max_values`: Some(1), `max_size`: Some(8), added: 503, mode: `MaxEncodedLen`)
	/// Storage: `People::OnboardingQueue` (r:2 w:2)
	/// Proof: `People::OnboardingQueue` (`max_values`: None, `max_size`: Some(973), added: 3448, mode: `MaxEncodedLen`)
	/// Storage: `People::OnboardingSize` (r:1 w:0)
	/// Proof: `People::OnboardingSize` (`max_values`: Some(1), `max_size`: Some(4), added: 499, mode: `MaxEncodedLen`)
	/// Storage: `People::RingsState` (r:1 w:0)
	/// Proof: `People::RingsState` (`max_values`: Some(1), `max_size`: Some(2), added: 497, mode: `MaxEncodedLen`)
	/// Storage: `People::PendingSuspensions` (r:1 w:0)
	/// Proof: `People::PendingSuspensions` (`max_values`: None, `max_size`: Some(93), added: 2568, mode: `MaxEncodedLen`)
	/// Storage: `People::Keys` (r:20 w:0)
	/// Proof: `People::Keys` (`max_values`: None, `max_size`: Some(56), added: 2531, mode: `MaxEncodedLen`)
	/// Storage: `People::People` (r:20 w:20)
	/// Proof: `People::People` (`max_values`: None, `max_size`: Some(99), added: 2574, mode: `MaxEncodedLen`)
	/// Storage: `People::ActiveMembers` (r:1 w:1)
	/// Proof: `People::ActiveMembers` (`max_values`: Some(1), `max_size`: Some(4), added: 499, mode: `MaxEncodedLen`)
	fn onboard_people() -> Weight {
		// Proof Size summary in bytes:
		//  Measured:  `6606`
		//  Estimated: `52470`
		// Minimum execution time: 164_330_000 picoseconds.
		Weight::from_parts(166_012_000, 52470)
			.saturating_add(RocksDbWeight::get().reads(50_u64))
			.saturating_add(RocksDbWeight::get().writes(27_u64))
	}
	/// Storage: `People::PendingSuspensions` (r:1 w:0)
	/// Proof: `People::PendingSuspensions` (`max_values`: None, `max_size`: Some(93), added: 2568, mode: `MaxEncodedLen`)
	fn pending_suspensions_iteration() -> Weight {
		// Proof Size summary in bytes:
		//  Measured:  `378`
		//  Estimated: `3558`
		// Minimum execution time: 3_305_000 picoseconds.
		Weight::from_parts(3_365_000, 3558)
			.saturating_add(RocksDbWeight::get().reads(1_u64))
	}
	/// Storage: `People::RingKeys` (r:1 w:1)
	/// Proof: `People::RingKeys` (`max_values`: None, `max_size`: Some(661), added: 3136, mode: `MaxEncodedLen`)
	/// Storage: `People::PendingSuspensions` (r:1 w:1)
	/// Proof: `People::PendingSuspensions` (`max_values`: None, `max_size`: Some(93), added: 2568, mode: `MaxEncodedLen`)
	/// Storage: `People::RingKeysStatus` (r:1 w:1)
	/// Proof: `People::RingKeysStatus` (`max_values`: None, `max_size`: Some(28), added: 2503, mode: `MaxEncodedLen`)
	/// Storage: `People::ActiveMembers` (r:1 w:1)
	/// Proof: `People::ActiveMembers` (`max_values`: Some(1), `max_size`: Some(4), added: 499, mode: `MaxEncodedLen`)
	/// Storage: `People::Root` (r:1 w:1)
	/// Proof: `People::Root` (`max_values`: None, `max_size`: Some(840), added: 3315, mode: `MaxEncodedLen`)
	/// The range of component `n` is `[1, 20]`.
	fn remove_suspended_keys(n: u32, ) -> Weight {
		// Proof Size summary in bytes:
		//  Measured:  `1955 + n * (4 ±0)`
		//  Estimated: `4305`
		// Minimum execution time: 5_132_935_000 picoseconds.
		Weight::from_parts(5_131_745_324, 4305)
			// Standard Error: 909_536
			.saturating_add(Weight::from_parts(2_227_614, 0).saturating_mul(n.into()))
			.saturating_add(RocksDbWeight::get().reads(5_u64))
			.saturating_add(RocksDbWeight::get().writes(5_u64))
	}
	/// Storage: `People::People` (r:1 w:1)
	/// Proof: `People::People` (`max_values`: None, `max_size`: Some(99), added: 2574, mode: `MaxEncodedLen`)
	/// Storage: `People::PendingSuspensions` (r:1 w:1)
	/// Proof: `People::PendingSuspensions` (`max_values`: None, `max_size`: Some(93), added: 2568, mode: `MaxEncodedLen`)
	/// Storage: `People::Keys` (r:2 w:2)
	/// Proof: `People::Keys` (`max_values`: None, `max_size`: Some(56), added: 2531, mode: `MaxEncodedLen`)
	/// Storage: `People::CounterForKeys` (r:1 w:1)
	/// Proof: `People::CounterForKeys` (`max_values`: Some(1), `max_size`: Some(4), added: 499, mode: `MaxEncodedLen`)
	/// Storage: `People::QueuePageIndices` (r:1 w:1)
	/// Proof: `People::QueuePageIndices` (`max_values`: Some(1), `max_size`: Some(8), added: 503, mode: `MaxEncodedLen`)
	/// Storage: `People::OnboardingQueue` (r:1 w:1)
	/// Proof: `People::OnboardingQueue` (`max_values`: None, `max_size`: Some(973), added: 3448, mode: `MaxEncodedLen`)
	fn migrate_keys_single_included_key() -> Weight {
		// Proof Size summary in bytes:
		//  Measured:  `1599`
		//  Estimated: `6052`
		// Minimum execution time: 29_265_000 picoseconds.
		Weight::from_parts(30_246_000, 6052)
			.saturating_add(RocksDbWeight::get().reads(7_u64))
			.saturating_add(RocksDbWeight::get().writes(7_u64))
	}
	/// Storage: `People::Keys` (r:29 w:0)
	/// Proof: `People::Keys` (`max_values`: None, `max_size`: Some(56), added: 2531, mode: `MaxEncodedLen`)
	/// Storage: `People::People` (r:29 w:29)
	/// Proof: `People::People` (`max_values`: None, `max_size`: Some(99), added: 2574, mode: `MaxEncodedLen`)
	/// Storage: `People::QueuePageIndices` (r:1 w:1)
	/// Proof: `People::QueuePageIndices` (`max_values`: Some(1), `max_size`: Some(8), added: 503, mode: `MaxEncodedLen`)
	/// Storage: `People::OnboardingQueue` (r:0 w:2)
	/// Proof: `People::OnboardingQueue` (`max_values`: None, `max_size`: Some(973), added: 3448, mode: `MaxEncodedLen`)
	fn merge_queue_pages() -> Weight {
		// Proof Size summary in bytes:
		//  Measured:  `4158`
		//  Estimated: `75636`
		// Minimum execution time: 176_828_000 picoseconds.
		Weight::from_parts(180_284_000, 75636)
			.saturating_add(RocksDbWeight::get().reads(59_u64))
			.saturating_add(RocksDbWeight::get().writes(32_u64))
	}
	/// Storage: `People::RingsState` (r:1 w:0)
	/// Proof: `People::RingsState` (`max_values`: Some(1), `max_size`: Some(2), added: 497, mode: `MaxEncodedLen`)
	/// Storage: `People::PendingSuspensions` (r:1 w:0)
	/// Proof: `People::PendingSuspensions` (`max_values`: None, `max_size`: Some(93), added: 2568, mode: `MaxEncodedLen`)
	/// Storage: `People::QueuePageIndices` (r:1 w:0)
	/// Proof: `People::QueuePageIndices` (`max_values`: Some(1), `max_size`: Some(8), added: 503, mode: `MaxEncodedLen`)
	/// Storage: `People::OnboardingQueue` (r:2 w:0)
	/// Proof: `People::OnboardingQueue` (`max_values`: None, `max_size`: Some(973), added: 3448, mode: `MaxEncodedLen`)
	fn on_poll_base() -> Weight {
		// Proof Size summary in bytes:
		//  Measured:  `1278`
		//  Estimated: `7886`
		// Minimum execution time: 12_389_000 picoseconds.
		Weight::from_parts(12_529_000, 7886)
			.saturating_add(RocksDbWeight::get().reads(5_u64))
	}
	/// Storage: `People::RingsState` (r:1 w:0)
	/// Proof: `People::RingsState` (`max_values`: Some(1), `max_size`: Some(2), added: 497, mode: `MaxEncodedLen`)
	/// Storage: `People::PendingSuspensions` (r:3 w:0)
	/// Proof: `People::PendingSuspensions` (`max_values`: None, `max_size`: Some(93), added: 2568, mode: `MaxEncodedLen`)
	/// Storage: `People::CurrentRingIndex` (r:1 w:0)
	/// Proof: `People::CurrentRingIndex` (`max_values`: Some(1), `max_size`: Some(4), added: 499, mode: `MaxEncodedLen`)
	/// Storage: `People::RingKeys` (r:1 w:0)
	/// Proof: `People::RingKeys` (`max_values`: None, `max_size`: Some(661), added: 3136, mode: `MaxEncodedLen`)
	/// Storage: `People::RingKeysStatus` (r:2 w:0)
	/// Proof: `People::RingKeysStatus` (`max_values`: None, `max_size`: Some(28), added: 2503, mode: `MaxEncodedLen`)
	/// Storage: `People::QueuePageIndices` (r:1 w:0)
	/// Proof: `People::QueuePageIndices` (`max_values`: Some(1), `max_size`: Some(8), added: 503, mode: `MaxEncodedLen`)
	/// Storage: `People::OnboardingQueue` (r:2 w:0)
	/// Proof: `People::OnboardingQueue` (`max_values`: None, `max_size`: Some(973), added: 3448, mode: `MaxEncodedLen`)
	/// Storage: `People::OnboardingSize` (r:1 w:0)
	/// Proof: `People::OnboardingSize` (`max_values`: Some(1), `max_size`: Some(4), added: 499, mode: `MaxEncodedLen`)
	fn on_idle_base() -> Weight {
		// Proof Size summary in bytes:
		//  Measured:  `818`
		//  Estimated: `8694`
		// Minimum execution time: 30_907_000 picoseconds.
		Weight::from_parts(31_628_000, 8694)
			.saturating_add(RocksDbWeight::get().reads(12_u64))
	}
	/// Storage: `People::AccountToAlias` (r:1 w:0)
	/// Proof: `People::AccountToAlias` (`max_values`: None, `max_size`: Some(120), added: 2595, mode: `MaxEncodedLen`)
	/// Storage: `People::Root` (r:1 w:0)
	/// Proof: `People::Root` (`max_values`: None, `max_size`: Some(840), added: 3315, mode: `MaxEncodedLen`)
	/// Storage: `System::Account` (r:1 w:1)
	/// Proof: `System::Account` (`max_values`: None, `max_size`: Some(128), added: 2603, mode: `MaxEncodedLen`)
	fn as_person_alias_with_account() -> Weight {
		// Proof Size summary in bytes:
		//  Measured:  `1345`
		//  Estimated: `4305`
		// Minimum execution time: 5_190_694_000 picoseconds.
		Weight::from_parts(5_196_672_000, 4305)
			.saturating_add(RocksDbWeight::get().reads(3_u64))
			.saturating_add(RocksDbWeight::get().writes(1_u64))
	}
	/// Storage: `People::AccountToPersonalId` (r:1 w:0)
	/// Proof: `People::AccountToPersonalId` (`max_values`: None, `max_size`: Some(56), added: 2531, mode: `MaxEncodedLen`)
	/// Storage: `System::Account` (r:1 w:1)
	/// Proof: `System::Account` (`max_values`: None, `max_size`: Some(128), added: 2603, mode: `MaxEncodedLen`)
	fn as_person_identity_with_account() -> Weight {
		// Proof Size summary in bytes:
		//  Measured:  `505`
		//  Estimated: `3593`
		// Minimum execution time: 12_960_000 picoseconds.
		Weight::from_parts(13_301_000, 3593)
			.saturating_add(RocksDbWeight::get().reads(2_u64))
			.saturating_add(RocksDbWeight::get().writes(1_u64))
	}
	/// Storage: `People::Root` (r:1 w:0)
	/// Proof: `People::Root` (`max_values`: None, `max_size`: Some(840), added: 3315, mode: `MaxEncodedLen`)
	/// Storage: `People::AccountToAlias` (r:1 w:0)
	/// Proof: `People::AccountToAlias` (`max_values`: None, `max_size`: Some(120), added: 2595, mode: `MaxEncodedLen`)
	fn as_person_alias_with_proof() -> Weight {
		// Proof Size summary in bytes:
		//  Measured:  `1099`
		//  Estimated: `4305`
		// Minimum execution time: 25_167_913_000 picoseconds.
		Weight::from_parts(25_204_118_000, 4305)
			.saturating_add(RocksDbWeight::get().reads(2_u64))
	}
	/// Storage: `People::People` (r:1 w:0)
	/// Proof: `People::People` (`max_values`: None, `max_size`: Some(99), added: 2574, mode: `MaxEncodedLen`)
	fn as_person_identity_with_proof() -> Weight {
		// Proof Size summary in bytes:
		//  Measured:  `754`
		//  Estimated: `3564`
		// Minimum execution time: 1_603_745_000 picoseconds.
		Weight::from_parts(1_606_019_000, 3564)
			.saturating_add(RocksDbWeight::get().reads(1_u64))
	}
	/// Storage: `People::AccountToAlias` (r:1 w:1)
	/// Proof: `People::AccountToAlias` (`max_values`: None, `max_size`: Some(120), added: 2595, mode: `MaxEncodedLen`)
	/// Storage: `People::Root` (r:1 w:0)
	/// Proof: `People::Root` (`max_values`: None, `max_size`: Some(840), added: 3315, mode: `MaxEncodedLen`)
	/// Storage: `System::Account` (r:1 w:1)
	/// Proof: `System::Account` (`max_values`: None, `max_size`: Some(128), added: 2603, mode: `MaxEncodedLen`)
	fn as_person_alias_with_account_revised() -> Weight {
		// Proof Size summary in bytes:
		//  Measured:  `1345`
		//  Estimated: `4305`
		// Minimum execution time: 25_323_961_000 picoseconds.
		Weight::from_parts(25_367_206_000, 4305)
			.saturating_add(RocksDbWeight::get().reads(3_u64))
			.saturating_add(RocksDbWeight::get().writes(2_u64))
	}
}
